---
- hosts: all
  tasks:
    - name: disable shutdown/hibernate on closing lid
      lineinfile:
        path: /etc/systemd/logind.conf
        line: "HandleLidSwitch=ignore"
        regexp: '(#\s*)?HandleLidSwitch.*'
        firstmatch: yes
        insertafter: regex
      notify:
        - restart systemd-logind
      become: yes

    - name: install Docker
      include_role:
        name: geerlingguy.docker
        apply:
          become:
            yes
      vars:
        docker_users:
          - hsop
  handlers:
    - name: restart systemd-logind
      service:
        name: systemd-logind
        state: restarted 
      become: yes
